# Generated by Django 4.1.13 on 2025-12-28 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrisData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sepal_length', models.FloatField(verbose_name='Çanak Yaprak Uzunluğu')),
                ('sepal_width', models.FloatField(verbose_name='Çanak Yaprak genişliği')),
                ('petal_length', models.FloatField(verbose_name='Taç Yaprak Uzunluğu')),
                ('petal_width', models.FloatField(verbose_name='Taç Yaprak Genişliği')),
                ('species', models.CharField(choices=[('Iris-setosa', 'Iris Setosa'), ('Iris-versicolor', 'Iris Versicolor'), ('Iris-virginica', 'Iris Virginica')], max_length=50, verbose_name='Çiçek Türü')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kaydeden Kullanıcı')),
            ],
        ),
    ]
