# Generated by Django 4.1.13 on 2025-12-28 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_irisdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Bölge adı')),
                ('city', models.CharField(max_length=50, verbose_name='Şehir')),
                ('country', models.CharField(max_length=50, verbose_name='Ülke')),
                ('elevation', models.IntegerField(default=0, verbose_name='Rakım')),
                ('description', models.TextField(blank=True, max_length=300, null=True, verbose_name='Bölge açıklaması')),
            ],
        ),
        migrations.AddField(
            model_name='irisdata',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.location', verbose_name='Konum bilgis'),
            preserve_default=False,
        ),
    ]
